Desafio7
arctouch-israelandrade/PrimeiroApp pull request #1
Opened 2024-04-19 18:16 UTC by arctouch-israelandrade

2024-04-22 16:45 UTC, arctouch-leonardomurca approved these changes

2024-04-22 17:02 UTC, arctouch-rogeriobaron requested changes
Fiz um comentário, com uma recomendação de mudança, para você ver Israel como é interagir em um Pull Request, recebendo feedback dos colegas e reportando ajustes :)

2024-04-22 17:02 UTC, arctouch-rogeriobaron commented on app/src/main/java/com/arctouch/primeiroapp/MainActivity.kt
> +                            composable("novatela") {
Para evitar bugs de navegação, é recomendado fazer:
você pode criar uma constante para o nome `"novatela"` e usar essa constante nova nessa linha e na tela `PerfilScreen.kt`, linha 94

Dessa forma, mesmo que você tenha um erro de digitação, ou precise modificar esse valor, não irá afetar o funcionamento da Navegação

2024-04-23 19:18 UTC, arctouch-rogeriobaron commented on app/src/main/java/com/arctouch/primeiroapp/MainActivity.kt
> +                            composable("novatela") {
@arctouch-israelandrade vi que você ja deletou a NovaTela. Sem problemas, só então não esqueça de aplicar as constantes que você criou, na navegação/rotas do app. 👍

2024-04-25 12:53 UTC, arctouch-rogeriobaron approved these changes

2024-04-25 12:53 UTC, merged