Corrigir testes unitarios
arctouch-israelandrade/PrimeiroApp pull request #10
Opened 2024-07-10 20:06 UTC by arctouch-israelandrade

- Adicionei as bibliotecas do mockK
- Troquei Perfildados para PerfilData
- Criei um objeto mock
- Alterei os testes para darem certo 
- E usei o verifySequence
- E o confirmverified

2024-07-11 14:47 UTC, arctouch-rogeriobaron requested changes

2024-07-11 14:47 UTC, arctouch-rogeriobaron commented on app/build.gradle.kts
> +    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.2")
Sabes dizer o motivo de adicionar essas bibliotecas? Podes remover elas?

2024-07-11 14:47 UTC, arctouch-rogeriobaron commented on app/src/main/java/com/arctouch/primeiroapp/repository/PerfilRepository.kt
> +    fun gravarDados(perfilData: PerfilData) {
👏

2024-07-11 14:47 UTC, arctouch-rogeriobaron commented on app/src/test/java/com/arctouch/primeiroapp/PerfilViewModelTest.kt
>  @RunWith(RobolectricTestRunner::class)
Dúvida: consegues remover essa anotação `@RunWith`? Acho que você não precisa mais dela. Sabes o motivo?

2024-07-11 16:48 UTC, arctouch-israelandrade commented on app/build.gradle.kts
> +    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.2")
Tive certa dificuldade para encontrar a versão correta do Mockk, então entrei no GitHub e encontrei essas implementações. Acabei adicionando sem saber sua função. Peço desculpas pelo erro e sim, posso removê-las.

2024-07-11 16:51 UTC, arctouch-israelandrade commented on app/build.gradle.kts
> +    testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:5.8.2")
Alterações feitas! obrigado pelo comentario!

2024-07-11 16:57 UTC, arctouch-israelandrade commented on app/src/test/java/com/arctouch/primeiroapp/PerfilViewModelTest.kt
>  @RunWith(RobolectricTestRunner::class)
Sim, consigo remover. Creio que não é mais necessário usar, pois não estou mais utilizando o Robolectric nos meus testes, mas não tenho certeza se esse é o motivo pelo qual devo remover.

2024-07-11 17:00 UTC, arctouch-israelandrade commented on app/src/test/java/com/arctouch/primeiroapp/PerfilViewModelTest.kt
>  @RunWith(RobolectricTestRunner::class)
Alterações feitas!

2024-07-11 19:21 UTC, arctouch-rogeriobaron approved these changes

2024-07-12 12:30 UTC, arctouch-elizedelabrida commented on app/src/main/java/com/arctouch/primeiroapp/repository/PerfilRepository.kt
> +    fun gravarDados(perfilData: PerfilData) {
👏 👏 👏 👏

2024-07-12 12:32 UTC, arctouch-elizedelabrida approved these changes

2024-07-12 12:32 UTC, merged