Uso de flow
arctouch-israelandrade/PrimeiroApp pull request #15
Opened 2024-10-28 18:46 UTC by arctouch-israelandrade

- Criei um classe de estados de Ui.
- Fiz a integração da classe de estado FilmesUiState na FilmesViewModel.
- Fiz a função Escutar o valor da variável uiState.
- Criei um lógica em que quando o uiState for igual ao Carregado, a tela recebe a lista de filmes.

2024-10-30 17:15 UTC, arctouch-elizedelabrida commented on app/src/main/java/com/arctouch/primeiroapp/DetailsScreen.kt
> +import androidx.lifecycle.ViewModel
Esses imports aqui na DetailsScreen acredito que não estão sendo usados, certo?
Você pode removê-los 😄 o atalho control + option + o faz isso automaticamente também

2024-10-30 17:17 UTC, arctouch-elizedelabrida commented on app/src/main/java/com/arctouch/primeiroapp/HomeScreen.kt
> +    viewModel.buscarFilmes()
Aqui você pode usar o atalho command + option + m para identar o arquivo (deixar ele alinhado) automaticamente =)

2024-10-30 17:24 UTC, arctouch-israelandrade commented on app/src/main/java/com/arctouch/primeiroapp/DetailsScreen.kt
> +import androidx.lifecycle.ViewModel
Feito!

2024-10-30 17:30 UTC, arctouch-elizedelabrida commented on app/src/main/java/com/arctouch/primeiroapp/HomeScreen.kt
> +    viewModel.buscarFilmes()
erro meu, é command + option + L para formatar hahaha perdão

2024-10-30 17:41 UTC, arctouch-israelandrade commented on app/src/main/java/com/arctouch/primeiroapp/HomeScreen.kt
> +    viewModel.buscarFilmes()
Prontinho!

2024-10-31 14:48 UTC, arctouch-rogeriobaron requested changes

2024-10-31 14:48 UTC, arctouch-rogeriobaron commented on app/src/main/java/com/arctouch/primeiroapp/MainActivity.kt
> +
Você pode deletar essa linha em branco extra?

2024-10-31 14:48 UTC, arctouch-rogeriobaron commented on app/src/main/java/com/arctouch/primeiroapp/HomeScreen.kt
> +    viewModel.buscarFilmes()
tem também umas linhas em branco a mais no arquivo, tipo a linha 49. Podes limpar isso também?

2024-10-31 14:48 UTC, arctouch-rogeriobaron commented on app/src/main/java/com/arctouch/primeiroapp/FilmesUiState.kt
> +    }
Posso estar errado, mas não estou vendo muita utilidade para essa `sealed interface` de `UiState`
Podes remover ela?

Aliás, podes transformar a `sealed class` de `FilmesUiState` para uma `sealed interface`?

Motivos para as mudanças:
- `UiState` não está sendo usada, só está deixando as coisas mais "verbosas" para escrever
- A ideia de mudar a `FilmesUiState` para uma `sealed interface` é que `FilmesUiState` não carrega nenhum atributo, então podemos deixar isso mais otimizado.


Dica: Quando falamos que algo está "verboso" é porque você precisa escrever mais do que o necessário para poder cumprir uma mesma função.

2024-10-31 14:48 UTC, arctouch-rogeriobaron commented on app/src/main/java/com/arctouch/primeiroapp/FilmesRepository.kt
>          apiService.buscarFilmes(CHAVE_API)
Agora que você está buscando os filmes da `apiService`, você pode remover a lista de filmes da linha 15 e usar os filmes da API.

2024-10-31 18:18 UTC, arctouch-israelandrade commented on app/src/main/java/com/arctouch/primeiroapp/FilmesRepository.kt
>          apiService.buscarFilmes(CHAVE_API)
Alterações Feitas, pode dar uma olhada?

2024-11-01 17:21 UTC, arctouch-israelandrade commented on app/src/main/java/com/arctouch/primeiroapp/FilmesRepository.kt
>          apiService.buscarFilmes(CHAVE_API)
Opa, tinha esquecido de fazer os commits, acho que agora foi!!!

2024-11-04 11:52 UTC, arctouch-elizedelabrida commented on app/src/main/java/com/arctouch/primeiroapp/FilmesViewModel.kt
> +   private val _uiState = MutableStateFlow<FilmesUiState>(FilmesUiState.Carregado(listOf()))
Você pode notar que essa linha está desalinhada com a linha abaixo, sendo que ambas estão no mesmo bloco, portanto, eram para estar alinhadas. Por favor, pode corrigir isso?

A identação do código é muito importante pois facilita muito ler o código, entender ele, dar manutenção, revisar etc

Lembre-se de sempre usar cmd + option + L pois ele alinha automaticamente o código para você

2024-11-04 11:53 UTC, arctouch-elizedelabrida commented on app/src/main/java/com/arctouch/primeiroapp/FilmesRepository.kt
> +
Retirar linha em vazio extra

2024-11-04 11:53 UTC, arctouch-elizedelabrida commented on app/src/main/java/com/arctouch/primeiroapp/FilmesUiState.kt
> +        data class Carregado(val filmes: List<com.arctouch.primeiroapp.models.Filme>) : FilmesUiState
Acertar identação do código nessa classe também, por favor, conforme comentado em https://github.com/arctouch-israelandrade/PrimeiroApp/pull/15/files#r1827612259

2024-11-04 11:54 UTC, arctouch-elizedelabrida commented on app/src/main/java/com/arctouch/primeiroapp/FilmesViewModel.kt
> +
Retirar linha em branco 26 que está vazia, por favor

2024-11-06 17:16 UTC, arctouch-israelandrade commented on app/src/main/java/com/arctouch/primeiroapp/FilmesViewModel.kt
> +
Feito, algo mais?

2024-11-08 13:44 UTC, arctouch-elizedelabrida approved these changes

2024-11-08 18:13 UTC, arctouch-rogeriobaron commented on app/src/main/java/com/arctouch/primeiroapp/FilmesUiState.kt
> +    data class Erro(val mensgem: String) : FilmesUiState
Eu acabei de notar, tem um pequeno typo (erro de digitação) aqui. O atributo aqui faltou um `a` em `mensgem`

2024-11-12 18:55 UTC, arctouch-rogeriobaron requested changes
Notei que o app não está compilando, podes checar e corrigir?

2024-11-13 17:07 UTC, arctouch-israelandrade commented
Creio que agora irá compilar.
OBS: O problema do elenco estar vindo duplicado e com \n será resolvido no próximo PR.

2024-11-13 23:15 UTC, arctouch-rogeriobaron commented
Ainda estou notando problemas de compilação em `FilmesUiState`, pode conferir?

2024-11-14 19:22 UTC, merged