invertendo as telas(Home e perfil)
arctouch-israelandrade/PrimeiroApp pull request #2
Opened 2024-04-24 17:37 UTC by arctouch-israelandrade

- Criei constantes para: Perfil, Home ,Detalhes e filmes
- Apos criadas as utilizei para inverter as telas(HomeScrenn e PerfilScrenn) 
OBS: cometi um erro de ter commitado a remoção da "nova-tela" na BRANCH: desafio7, Mas ja foi removida do app

2024-04-25 13:08 UTC, arctouch-leonardomurca commented
Tome cuidado ao nomear suas branches. Observe que o nome da branch ficou como `"refatora\u00E7\u00E3oinicial-telas"`. Evite colocar acentuações e caracteres complexos como "ç". Recomendo o seguinte padrão: `refatoracao-inicial-tela`

2024-04-25 13:08 UTC, arctouch-leonardomurca requested changes

2024-04-25 20:25 UTC, arctouch-rogeriobaron requested changes

2024-04-25 20:25 UTC, arctouch-rogeriobaron commented on app/src/main/java/com/arctouch/primeiroapp/MainActivity.kt
>                          TopAppBar(title = { Text("Movies APP") }, navigationIcon = {
Notei um detalhe:
o botão para a tela de perfil deveria estar a direita, cfe o desafio, certo? @arctouch-leonardomurca 

@arctouch-israelandrade vc pode ajustar isso trocando o  argumento `navigationIcon` para `actions` para resolver isso.

2024-04-25 20:25 UTC, arctouch-rogeriobaron commented on app/src/main/java/com/arctouch/primeiroapp/MainActivity.kt
> +                                Icon(Icons.Default.Person, contentDescription = "Back")
Detalhe pequeno (ou `nitpick` em inglês):

`contentDescription`, que é usado para acessbilidade, sugere que o botão ainda é de voltar.

2024-04-25 20:25 UTC, arctouch-rogeriobaron commented on app/src/main/java/com/arctouch/primeiroapp/PerfilScreen.kt
> +        Button(onClick = { navController.navigate(HOME) }) {
@arctouch-leonardomurca notei agora que a tela de perfil não tem a barra de navegação e o botão voltar. Vamos colocar a barra de volta?

2024-04-26 17:04 UTC, arctouch-leonardomurca commented on app/src/main/java/com/arctouch/primeiroapp/PerfilScreen.kt
> +        Button(onClick = { navController.navigate(HOME) }) {
Acredito que devemos voltar com a barra de navegação. cc: @arctouch-israelandrade

2024-04-26 17:31 UTC, arctouch-israelandrade commented on app/src/main/java/com/arctouch/primeiroapp/PerfilScreen.kt
> +        Button(onClick = { navController.navigate(HOME) }) {
Ja adicionei novamente!

2024-04-29 19:44 UTC, arctouch-rogeriobaron approved these changes

2024-04-30 12:11 UTC, arctouch-leonardomurca approved these changes

2024-04-30 12:11 UTC, merged