Ajustes de arquitetura
arctouch-israelandrade/PrimeiroApp pull request #20
Opened 2024-12-23 17:41 UTC by arctouch-israelandrade

- Removi a interface parcelable e a anotação
- Separei a data class com.arctouch.primeiroapp.Filme no seu próprio arquivo, no pacote models.
- Movi a data class com.arctouch.primeiroapp.repository.PerfilData para o pacote models.
- Deletei uma class solta.
- Movi a classe FilmesRepository para o pacote repository

2024-12-26 14:23 UTC, arctouch-rogeriobaron requested changes

2024-12-26 14:23 UTC, arctouch-rogeriobaron commented on app/src/main/java/com/arctouch/primeiroapp/models/Filme.kt
> +) : Parcelable
@arctouch-israelandrade ficou faltando remover o `Parcelable` e a anotação 😬

2024-12-27 18:04 UTC, arctouch-israelandrade commented on app/src/main/java/com/arctouch/primeiroapp/models/Filme.kt
> +) : Parcelable
Pode dar uma verificada?

2025-01-02 17:33 UTC, arctouch-elizedelabrida approved these changes

2025-01-02 21:38 UTC, arctouch-rogeriobaron approved these changes

2025-01-02 21:38 UTC, merged