utilizando SharedPreferences
arctouch-israelandrade/PrimeiroApp pull request #5
Opened 2024-05-15 20:28 UTC by arctouch-israelandrade

Bom, aqui estão algumas mudanças:

- Criei um val para o sharedPref
- Criei um sharedPref para idade e nome 
- No button, criei um editor e com isso 
- Fiz um putstring para "nome" e "idade"
- Fiz um apply

2024-05-16 13:15 UTC, elizedelabrida commented on app/src/main/java/com/arctouch/primeiroapp/PerfilScreen.kt
> +            val editor = sharedPref.edit()
Esse comentário é só um lembrete sobre o que falamos ontem:

Como conversamos, idealmente esses comportamentos não ficariam aqui dentro da `PerfilScreen` pois esses comportamentos de edição e buscar dados já seriam uma lógica diferente da tela, e não queremos que essa classe fique grande demais ou que tenha responsabilidades demais, seguindo o princípio que falamos sobre refatoração, agora que está funcionando para coletar os dados do shared preferences, o ideal agora seria refatorar 😄 

Já existe uma tarefa no quadro para, após entender o que é uma view model, refatorar esse lógica de gravação para ficar em outra classe, então no futuro essa refatoração já está prevista para ser feita 🙌

2024-05-16 13:58 UTC, arctouch-rogeriobaron requested changes

2024-05-16 13:58 UTC, arctouch-rogeriobaron commented on app/src/main/java/com/arctouch/primeiroapp/PerfilScreen.kt
>      var nome: String by rememberSaveable { mutableStateOf("") }
`nome` pode ser removido pois não está sendo utilizado 😉

2024-05-16 13:58 UTC, arctouch-rogeriobaron commented on app/src/main/java/com/arctouch/primeiroapp/PerfilScreen.kt
> +        "PrimeiroAppSharedPreferences", Context.MODE_PRIVATE)
Sugestão: essa String de identificação do `SharedPreferences` é legal separar em uma constante. Essa informação não deve sofrer alterações para não perder os dados

2024-05-16 13:58 UTC, arctouch-rogeriobaron commented on app/src/main/java/com/arctouch/primeiroapp/PerfilScreen.kt
> +    val nomeSharedPreferences = sharedPref.getString("nome", "-") ?: ""
para buscar, **e depois gravar** os dados no `SharedPreferences`, seria legal colocar esses identificadores de `"idade"` e `"nome"` como constantes também, isso evita problemas com erros

2024-05-16 17:13 UTC, arctouch-israelandrade commented on app/src/main/java/com/arctouch/primeiroapp/MainActivity.kt
> +        val sharedPref = activity.getPreferences(Context.MODE_PRIVATE)
Alterações feitas Elize!

2024-05-16 17:17 UTC, arctouch-israelandrade commented on app/src/main/java/com/arctouch/primeiroapp/PerfilScreen.kt
> +    val nomeSharedPreferences = sharedPref.getString("nome", "-") ?: ""
Acabei de fazer os commits com as alterações!

2024-05-17 13:29 UTC, arctouch-rogeriobaron requested changes

2024-05-17 13:29 UTC, arctouch-rogeriobaron commented on app/src/main/java/com/arctouch/primeiroapp/PerfilScreen.kt
> +const val IDADE = "idade"
Uma boa prática para nomes, principalmente de constantes é ser um pouco mais específico sobre o que se trata a informação.

Sugestões (seguindo o padrão `Screaming Snake case, para constantes`):
```
const val PRIMEIRO_APP_SHARED_PREFERNCES = "PrimeiroAppSharedPreferences"
const val SHARED_PREFS_NOME = "nome"
const val SHARED_PREFS_IDADE = "idade"
```

2024-05-17 18:12 UTC, arctouch-rogeriobaron commented on app/src/main/java/com/arctouch/primeiroapp/PerfilScreen.kt
> +            editor.putString("idade", idadeSalva)
não esqueça de aplicar a constante para cá também, nas linhas 86 e 87

2024-05-20 16:58 UTC, rogerioit approved these changes

2024-05-20 17:00 UTC, arctouch-rogeriobaron approved these changes

2024-05-20 17:00 UTC, merged

2024-05-20 17:00 UTC, arctouch-israelandrade commented on app/src/main/java/com/arctouch/primeiroapp/PerfilScreen.kt
> +            editor.putString("idade", idadeSalva)
Acabei de fazer as alterações