Melhorando UI tela detalhes
arctouch-israelandrade/PrimeiroApp pull request #8
Opened 2024-06-07 17:50 UTC by arctouch-israelandrade

- Adicionei um padding na tela de detalhes
- Troquei a cor da tela de preto para cinza
- Troquei a cor da letra de branco para preto
- Criei uma lista de pontos para o elenco
- Coloquei um emoji antes dos títulos dos filmes

OBS:  Tem alguns commits que estão relacionados à branch "viewModel" porque eu tinha esquecido de sincronizar com a branch principal.

2024-06-13 16:19 UTC, arctouch-leonardomurca requested changes
Qualquer dúvida, estou à disposição!

2024-06-13 16:19 UTC, arctouch-leonardomurca commented on app/src/main/java/com/arctouch/primeiroapp/HomeScreen.kt
> +            " \uD83C\uDFA5 Poderoso Chefão",
O que esse código significa? Ficaria mais claro se você extraísse esse código para uma variável com um nome bem descritivo, assim como fez com o `val bullet = "\u2022"`.

2024-06-13 16:19 UTC, arctouch-leonardomurca commented on app/src/main/java/com/arctouch/primeiroapp/ViewModelActivity.kt
> +        return PerfilDados (idadeSharedPreferences, nomeSharedPreferences)
Espaço desnecessário. Pode remover? Fique atento à essas formatações, porque acaba que o diff do Pull Request fica poluído e dificulta na revisão.

2024-06-13 16:19 UTC, arctouch-leonardomurca commented on app/src/main/java/com/arctouch/primeiroapp/DetailsScreen.kt
> +                    },
Seria interessante você aplicar uma refatoração aqui chamada [Extract Function](https://refactoring.com/catalog/extractFunction.html). 
Dicas: 
- Dê um nome bem descritivo para essa nova função;
- Mova as variáveis `paragraphStyle` e `bullet` para o escopo dessa nova função.

2024-06-14 13:30 UTC, arctouch-elizedelabrida commented on app/build.gradle.kts
> +    implementation("androidx.room:room-ktx:2.6.1")
Olá @arctouch-israelandrade! Perdão se a pergunta for muito óbvia, mas foi necessário adicionar a biblioteca do room aqui por algum motivo em específico?

2024-06-17 17:33 UTC, arctouch-israelandrade commented on app/src/main/java/com/arctouch/primeiroapp/HomeScreen.kt
> +            " \uD83C\uDFA5 Poderoso Chefão",
Leo, criei a val para o emoji e ja adicionei em todos os filmes!

2024-06-18 12:32 UTC, arctouch-elizedelabrida approved these changes

2024-06-18 16:53 UTC, arctouch-rogeriobaron approved these changes

2024-06-24 18:09 UTC, arctouch-leonardomurca approved these changes
LGTM

2024-06-24 18:10 UTC, merged